# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
    rust: latest
  jobs:
    pre_install:
      - python -m pip install maturin
    post_install:
      - maturin build
      - python -m pip install --user --break-system-packages --force-reinstall target/wheels/*.whl
sphinx:
  configuration: docs/source/conf.py
