[package]
name = "pyrtls"
version = "0.1.0"
authors = ["Dirkjan Ochtman <dirkjan@ochtman.nl>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.17"
rustls = "0.20.6"
rustls-native-certs = "0.6.2"
socket2 = "0.4"
